### ISSUE TITLE
Optimizations / CustomError Support ?

### ISSUE THREAD

**Issue by MentalGear** [DavidWells/safe-await#3]
Thanks for this lib. Wondering if it also throws exceptions for custom errors.

Also this guy has as well a maybe even shorter way to handle it:
https://www.maxpou.fr/async-await-without-try-catch

```
export function to(promise) {
  return promise
    .then(data => [null, data])
    .catch(err => [err, null]);
}

const [err, response] = await to(http.get('https://api.github.com/users/maxpou'))

if (err) {
  // error handling
}

// do something

```

**Comment by DavidWells** [comment]
Only throws for nativeErrors https://github.com/DavidWells/safe-await/blob/master/lib/index.js#L5
